### ISSUE TITLE
Ubuntu related releases should use the oldest version aviable

### ISSUE THREAD

**Issue by Kastakin** [trappitsch/fbs-release-github-actions#2]
As stated on the PyInstaller docs is advisable when building on Linux to [always build your app on the oldest version of GNU/Linux you mean to support.](https://pyinstaller.readthedocs.io/en/stable/usage.html#making-gnu-linux-apps-forward-compatible)

I've created a pull request (#1) where I've edited the version of Ubuntu used in both `release-ubuntu.yml` and `release-multi-os.yml` to [the oldest version available for the GitHub runners](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by trappitsch** [comment]
Great catch, thanks @Kastakin
