### ISSUE TITLE
Upload Release Asset macOS (3.6) - Permission denied on fbs/installer/mac/create-dmg/create-dmg

### ISSUE THREAD

**Issue by 94929** [trappitsch/fbs-release-github-actions#3]
Hi, I get the following error when running the "Upload Release Asset macOS (3.6)" action, inside the multi-platform action.
<img width="1284" alt="Screen Shot 2021-04-01 at 11 09 08 AM" src="https://user-images.githubusercontent.com/10961008/113233839-11428f80-92db-11eb-95b2-efea9b89882f.png">

This is the error I get when running `fbs installer` on my mac.
Any help would be appreciated.

Thanks in advance.

**Comment by trappitsch** [comment]
Are you saying that you get this issue as well on your Mac or only when running the GitHub action?

**Comment by 94929** [comment]
Hey, sorry for the confusion.

> Are you saying that you get this issue as well on your Mac or only when running the GitHub action?

I'm getting that error on both cases, (1) running fbs locally and (2) running on the Github action.

**Comment by darenliang** [comment]
I've been running into the same issue. It doesn't seem to be a GitHub actions issue, rather there's something wrong going on with fbs' packages.

The file `create-dmg` doesn't seem to have execute permissions and some files in fbs installer are weirdly formatted leading to a second unrelated problem. Giving `create-dmg` file execute permissions and using dos2unix over the packages seems to work.

In between `Install python dependencies` and `Run fbs` steps:
```yml
- name: Monkey patch
  run: |
    PYTHON_VERSION=`python --version | awk '{print $2}'`
    find $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION -name create-dmg -type f -exec chmod +x {} +
    brew install dos2unix
    find $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION -type f -print0 | xargs -0 dos2unix
```

This is the workflow file that I've been using to get multi-os working: https://github.com/darenliang/dsgui/blob/master/.github/workflows/release-multi-os.yml

It's not really a solution, but I don't see any other way to fix the issue other than a fbs hotfix.

**Comment by 94929** [comment]
> I've been running into the same issue. It doesn't seem to be a GitHub actions issue, rather there's something wrong going on with fbs' packages.
> 
> The file `create-dmg` doesn't seem to have execute permissions and some files in fbs installer are weirdly formatted leading to a second unrelated problem. Giving `create-dmg` file execute permissions and using dos2unix over the packages seems to work.
> 
> In between `Install python dependencies` and `Run fbs` steps:
> 
> ```yaml
> - name: Monkey patch
>   run: |
>     PYTHON_VERSION=`python --version | awk '{print $2}'`
>     find $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION -name create-dmg -type f -exec chmod +x {} +
>     brew install dos2unix
>     find $RUNNER_TOOL_CACHE/Python/$PYTHON_VERSION -type f -print0 | xargs -0 dos2unix
> ```
> 
> This is the workflow file that I've been using to get multi-os working: https://github.com/darenliang/dsgui/blob/master/.github/workflows/release-multi-os.yml
> 
> It's not really a solution, but I don't see any other way to fix the issue other than a fbs hotfix.

This proposed method works! Thanks for letting me know!

**Comment by trappitsch** [comment]
thanks for all the comments and sorry for the delay. this seems to be, as mentioned, an issue with fbs and should probably be raised there. does the github action for the minimal example on fbs fail as well?

**Comment by darenliang** [comment]
The same issue was raised here: https://github.com/mherrmann/fbs/issues/233

I haven't tested the GitHub action for the minimal example, but I'm quite sure the same issue will occur.

**Comment by mherrmann** [comment]
fbs author here. Which version of fbs are you using?

**Comment by trappitsch** [comment]
As @darenliang noted, this seems to be unrelated to the Action at this point. thanks @mherrmann for your comment and for chiming in. currently the action as I designed it uses simply `pip install fbs` from PyPi. I'm planning on testing out integrating the new fbs pro with the download link integrated as a github secret. That should work fairly straight forward, but I'm lacking a bit of time right now to test it.

**Comment by mherrmann** [comment]
I see. I think I know what the problem was: I created the release file for fbs 0.9.2 on Windows. This must have created the `create-dmg` file with CRLF line endings instead of LF. I re-uploaded fbs 0.9.3 built on Linux now. Please let me know if you still encounter issues.

**Comment by darenliang** [comment]
I tried testing it on my local machine and fbs 0.9.3 works now.

I think using LF did the trick.

Thanks for the quick response!

**Comment by mherrmann** [comment]
Thank you for letting me know!

**Comment by trappitsch** [comment]
Looks like this is solved, thanks everybody. Closing.
